spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/exception
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximumPoolSize: 3
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
